### PR TITLE
Update the PHP 7.4 Docker image [MAILPOET-5726]

### PR DESCRIPTION
**Pull request by lysyjan**
## Description

_N/A_

## Code review notes

Because CircleCI started using different images, we needed to update the image with PHP 7.4.

## QA notes

_N/A_

## Linked PRs

https://github.com/mailpoet/mailpoet/pull/5318
https://github.com/mailpoet/mailpoet-premium/pull/826

## Linked tickets

[MAILPOET-5726]

## After-merge notes

_N/A_

[MAILPOET-5726]: https://mailpoet.atlassian.net/browse/MAILPOET-5726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by triple0t — COMMENTED** [review]
What is the function of this line: https://github.com/mailpoet/wordpress-images/blob/d3d15433bbf9aca4cab6a71f5526f1e54f86339b/7.4/Dockerfile#L21-L24

It appears you are removing the memory limit on circleci. Why are you doing that?

**Comment by lysyjan** [comment]
@triple0t It's based on the previous versions, such as 7.3 or 7.2; because there are no comments, I am not sure about that.
I wanted to avoid unexpected failures after using this image, so I copied it. I'm expecting it's due to static analysis or something like that.

**Comment by triple0t** [comment]
> It's based on the previous versions, such as 7.3 or 7.2; because there are no comments, I am not sure about that.
I wanted to avoid unexpected failures after using this image, so I copied it. I'm expecting it's due to static analysis or something like that.

Hmmm, okay.

> bcmath mysqli pdo pdo_mysql zip gd

Why did you stop installing these extensions?
Do they come preinstalled with the `cimg/php:7.4` docker image?

**Comment by triple0t** [comment]
Also, Please add the linked ticket and other related PRs to the description

**Review by triple0t — APPROVED** [review]
LGTM

**Pull request merged**
