### PR TITLE
Create wp 5.0 with php7.1 image [MAILPOET-3144]

### PR DESCRIPTION
**Pull request by pavel-mailpoet**
[MAILPOET-3144]

[MAILPOET-3144]: https://mailpoet.atlassian.net/browse/MAILPOET-3144

### CODE REVIEW

**Comment by wxa** [comment]
@pavel Should this image be added to Makefile?

**Comment by pavel-mailpoet** [comment]
@wxa I added it to the file.

**Comment by wxa** [comment]
@pavel-mailpoet Do we still need PHP 7.0 images and Makefile commands here?

**Comment by pavel-mailpoet** [comment]
@wxa true, I removed both. I removed PHP 7.0 images. And I also removed the Makefile because we cannot use it anyway and I updated readme instead.

**Review by wxa — APPROVED** [review]

**Review by veljkho — APPROVED** [review]

**Pull request merged**
